server:
  port: 8081

spring:
  application:
    name: GATEWAY-SERVICE
  data:
    redis:
      host: localhost
      port: 6379
#  cloud:
#    gateway:
#      routes:
#        - id: sevice1module
#          uri: http://127.0.0.1:8081/
#          predicates:
#            - Path=/service1/**
#        - id: sevice2module
#          uri: http://127.0.0.1:8082/
#          predicates:
#            - Path=/service2/**

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9091/eureka
    instance:
      hostname: http://localhost

spring.security.oauth2:
  resourceserver:
    jwt:
      jwk-set-uri: ${URL_AUTH:http://localhost}:8080/realms/timbeck/protocol/openid-connect/certs
  client:
    provider:
      keycloak:
        issuer-uri: ${URL_AUTH:http://localhost}:8080/realms/timbeck
    registration:
      spring-with-test-scope:
        provider: keycloak
        client-id: timbeck-openid
        authorization-grant-type: authorization_code
        scope: openid
