server:
  port: 8081


spring:
  application:
    name: GATEWAY-SERVICE
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${URL_AUTH:http://localhost}:8080/realms/arquiteturag1/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: ${URL_AUTH:http://localhost}:8080/realms/arquiteturag1
        registration:
          spring-with-test-scope:
            provider: keycloak
            client-id: arquitetura_client
            clientSecret: NOKtorbenz86ixRhtb3x6b9H5KjgMFju
            authorization-grant-type: authorization_code
            scope: openid

  cloud:
    gateway:
      routes:
        - id: sevice1module
          uri: http://127.0.0.1:8082/
          predicates:
            - Path=/service1/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 5
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@KeyResolverConfiguration}"
        - id: sevice2module
          uri: http://127.0.0.1:8083/
          predicates:
            - Path=/service2/**
        - id: authmodule
          uri: http://127.0.0.1:8080/
          predicates:
            - Path=/auth/**

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9091/eureka
    instance:
      hostname: http://localhost

#spring.security.oauth2:
#  resourceserver:
#    jwt:
#      jwk-set-uri: ${URL_AUTH:http://localhost}:8080/realms/timbeck/protocol/openid-connect/certs
#  client:
#    provider:
#      keycloak:
#        issuer-uri: ${URL_AUTH:http://localhost}:8080/realms/timbeck
#    registration:
#      spring-with-test-scope:
#        provider: keycloak
#        client-id: timbeck-openid
#        authorization-grant-type: authorization_code
#        scope: openid
#spring.security.oauth2:
#  resourceserver:
#    jwt:
#      issuer-uri: ${URL_AUTH:http://localhost:8080}
#      jwk-set-uri: ${URL_AUTH:http://localhost:8080}/oauth2/jwks

