spring:
  application:
    name: service2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${URL_AUTH:http://localhost:8080}
          jwk-set-uri: ${URL_AUTH:http://localhost:8080}/oauth2/jwks

server:
  port: 8083
  servlet:
    context-path: /service2
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:9091/eureka}