spring:
  application:
    name: service2
  security:
    oauth2:
      resourceserver:
        jwt:
          #          issuer-uri: ${URL_AUTH:http://localhost:8080/auth}
          #          jwk-set-uri: ${URL_AUTH:http://localhost:8080/auth}/oauth2/jwks
          jwk-set-uri: ${URL_AUTH:http://localhost}:8080/realms/arquiteturag1/protocol/openid-connect/certs

server:
  port: 8083
  servlet:
    context-path: /service2
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:9091/eureka}