spring:
  application:
    name: service1
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: ${URL_AUTH:http://localhost:8080/auth}
#          jwk-set-uri: ${URL_AUTH:http://localhost:8080/auth}/oauth2/jwks
          jwk-set-uri: http://localhost:8080/realms/arquiteturag1/protocol/openid-connect/certs

server:
  port: 8082
  servlet:
    context-path: /service1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka